version: '3'
services:
  db:
    image: mysql:latest
    container_name: simple-forum-database
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=simple-forum
    volumes:
      - "D:/Data/simple-forum:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1